### ISSUE TITLE
Proposed general architecture

### ISSUE THREAD

**Issue by dselmanovic** [Joystream/youtube-synch#10]
The diagram here shows general system architecture based on AWS services.

![Youtube Downloader  (2)](https://user-images.githubusercontent.com/7916640/135263007-d99b728c-3cb1-4f08-9622-b48b72c8e0a2.png)

1. Create a database of users and channels to be monitored for downloads. This database would be structured to allow any number of users to register any number of YouTube channels.

2. Create a AWS Lambda function that would execute in predefined time intervals (ex. 5 min). This lambda function would retrieve a list of available videos per channel and save the list in the DB. Every new video that is discovered by this Lambda would be recorded in "Inbound" database for processing/download.

3. Create NodeJS based video downloader and create a docker image that will be executed for each individual download. Downloaders would be orchestrated by AWS Container services and kubernetes which would allow full scalability. Video downloader will be responsible for the following:
       - Download video from youtube
       - Upload video to dedicated AWS S3 bucket
       - Record reference to S3 file in User/Channel Database
       - Mark downloaded video in Inbound DB
Once the download process for an individual video is completed, the docker container will be removed.

4. Initiator Lambda would, similar to Youtube Monitor Lambda, run in regular time intervals and initiate the download of the pre-configured number of videos by spinning download containers.

This architecture allows controlled scalability and cost management because setting how often videos are downloaded and the number of downloads per interval gives us full control.

Once again, I would like to remind you to verify the terms of use for Youtube and confirm that we can download a large number of videos without triggering YouTube security which might cause them to block our IP for accessing their services.

**Comment by bedeho** [comment]
Thank you for this, I have a few questions

- Why should we have two distinct databases? One for channels, and one for videos detected under these channels? It would seem simpler to have one source of truth, and also the benefit of the referential integrity checks of having everything in one schema? e.g. making sure a video x is listed as part of channel y, which has to be known to exist, and one cannot remove a channel y if there are lots of inbound videos, etc.
- What level of state about each video should recorded ? For example, it would seem you would want to track each possible step of the life-cycle of a video, such as: 
  - `discovered(x)`: discovered at time `x`
  - `download_initiated(x,y)`: a downloader was started at time `x` with process id `y`
  - `download_interrupted(x):` a download was interrupted for some reason, e.g. connection lost, our infra died, etc.
  - `download_completed(x)`: a download was successfully completed
  - `uploaded_to_joystream_initated`: ...
  - `uploaded_to_joystream_failed`: ...
  - `uploaded_to_joystream_succeeded`: ...
  and possibly many other complex variations. This kind of information would give very rich visibility into the full state of the system at any given time, for example allowing us to give a given user an understanding of how synching is progressing for their particular channel. It would seem that this sort of state would also be required if you want to gracefully do something like remove a channel, which would require the ability to identify all running downloaders corresponding to the given channel, so as to be able to halt them.
- Do you have any initial thoughts how the part of he system which does the uploading to our system would fit in here? Would you for example have each downloader try to publish what it had successfully downloaded? I guess one thing to keep in mind here is that blockchain throughput is not unconstrained, hence it could make sense to perhaps queue these publications from this system, so that it plays nice with all other unrelated users of the chain, and even allow for whole sale pausing or rate control, in order to take advantage of times where blockchain fees are lower.
- It would be great if the `User/channels` dbase could include information about how to possibly priorities each channel, for example use the signup date to prioritize at least initiation synch of new users, so they dont have to wait forever to at least see things starting to get populated. Another thing which could be taken into account would be follower counts, so that channels with higher follower counts are prioritised to some extent. I guess if `Inbound` & `Users/channels` are kept separate going forward, some of this information should be in the former, not the latter, as downloading is likely where most of the time is required, not monitoring.
- In general, I would love to see the schemas you have in mid for the databases, perhaps in a diagram, in order to have a more concrete understanding of what state will live where.

**Comment by dselmanovic** [comment]
# Youtube Downloader

## Youtube Monitor Service

Youtube Monitor Service will use Google Youtube API to retrieve channel info, playlists, and videos information for a registered youtube username.

The service will be created as AWS Lambda and it will be scheduled to constantly monitor all registered users and discover new videos that need to be downloaded.

The Monitor will:
1. Download list of Channels owned by the user
2. Download list of Playlists for each Channel
3. Download list of Videos for each Playlist
4. Download detailed information for a specific video
5. Download Thumbnal images for Channels, Playlists, and Videos as they are discovered and save them to a dedicated AWS S3 Bucket

### Get the list of Youtube Channels owned by a user

**Request:**
```
curl \
  'https://youtube.googleapis.com/youtube/v3/channels?part=snippet%2CcontentDetails%2Cstatistics&forUsername=GoogleDevelopers&key=[YOUR_API_KEY]' \
  --header 'Authorization: Bearer [YOUR_ACCESS_TOKEN]' \
  --header 'Accept: application/json' \
  --compressed
```
**Response example:**
```
{
  "kind": "youtube#channelListResponse",
  "etag": "0eg2KFgVjw32VDgHYNOJB9hEV4s",
  "pageInfo": {
    "totalResults": 1,
    "resultsPerPage": 5
  },
  "items": [
    {
      "kind": "youtube#channel",
      "etag": "2Jj5FrI_kZx3A-U4zm-9oCKGxtE",
      "id": "UC_x5XG1OV2P6uZZ5FSM9Ttw",
      "snippet": {
        "title": "Google Developers",
        "description": "The Google Developers channel features talks from events, educational series, best practices, tips, and the latest updates across our products and platforms.\n\nSubscribe to Google Developers → https://goo.gle/developers\n",
        "customUrl": "googledevelopers",
        "publishedAt": "2007-08-23T00:34:43Z",
        "thumbnails": {
          "default": {
            "url": "https://yt3.ggpht.com/ytc/AKedOLSsnWm_dQzIqM-qgW74yebXNX_b__k6WAeUBb6GeGQ=s88-c-k-c0x00ffffff-no-rj",
            "width": 88,
            "height": 88
          },
          "medium": {
            "url": "https://yt3.ggpht.com/ytc/AKedOLSsnWm_dQzIqM-qgW74yebXNX_b__k6WAeUBb6GeGQ=s240-c-k-c0x00ffffff-no-rj",
            "width": 240,
            "height": 240
          },
          "high": {
            "url": "https://yt3.ggpht.com/ytc/AKedOLSsnWm_dQzIqM-qgW74yebXNX_b__k6WAeUBb6GeGQ=s800-c-k-c0x00ffffff-no-rj",
            "width": 800,
            "height": 800
          }
        },
        "localized": {
          "title": "Google Developers",
          "description": "The Google Developers channel features talks from events, educational series, best practices, tips, and the latest updates across our products and platforms.\n\nSubscribe to Google Developers → https://goo.gle/developers\n"
        },
        "country": "US"
      },
      "contentDetails": {
        "relatedPlaylists": {
          "likes": "",
          "uploads": "UU_x5XG1OV2P6uZZ5FSM9Ttw"
        }
      },
      "statistics": {
        "viewCount": "186294622",
        "subscriberCount": "2200000",
        "hiddenSubscriberCount": false,
        "videoCount": "5414"
      }
    }
  ]
}
```
---
### Get the list of Playlists in a Channel
*Note:*
To get the list of **uploaded** videos use the ```contentDetails.relatedPlaylists``` from the previous response from Channel details

**Request:**
```
curl \
  'https://youtube.googleapis.com/youtube/v3/playlists?part=snippet%2CcontentDetails&channelId=UC_x5XG1OV2P6uZZ5FSM9Ttw&maxResults=25&key=[YOUR_API_KEY]' \
  --header 'Authorization: Bearer [YOUR_ACCESS_TOKEN]' \
  --header 'Accept: application/json' \
  --compressed
```

**Response example:**
```
{
  "kind": "youtube#playlistListResponse",
  "etag": "7jdLvB-_XIPW33RPExY9bs2egFg",
  "nextPageToken": "CBkQAA",
  "pageInfo": {
    "totalResults": 472,
    "resultsPerPage": 25
  },
  "items": [
    {
      "kind": "youtube#playlist",
      "etag": "fVUN6HlEMV1vVyarss6HTbFPzH8",
      "id": "PLOU2XLYxmsIJyGVT-ol1u1TX0AR_mAtmx",
      "snippet": {
        "publishedAt": "2021-09-20T21:39:37Z",
        "channelId": "UC_x5XG1OV2P6uZZ5FSM9Ttw",
        "title": "Meghan's Magical Playlist",
        "description": "Meet Meghan Mehta, a Developer Relations Engineer on the Android team working on Android education, Security, and Privacy. \n\nWe asked her to create a playlist of her must watch videos, she delivered a playlist full of fun and educational content ranging from all things Android, gymnastics, and music. Thanks Meghan!\n#WhatDevelopersWatch\n\nSubscribe to Google Developers → https://goo.gle/developers\n\nSubscribe to Android Developers → https://goo.gle/androiddevs",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/ZTDXo0-SKuU/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/ZTDXo0-SKuU/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/ZTDXo0-SKuU/hqdefault.jpg",
            "width": 480,
            "height": 360
          },
          "standard": {
            "url": "https://i.ytimg.com/vi/ZTDXo0-SKuU/sddefault.jpg",
            "width": 640,
            "height": 480
          },
          "maxres": {
            "url": "https://i.ytimg.com/vi/ZTDXo0-SKuU/maxresdefault.jpg",
            "width": 1280,
            "height": 720
          }
        },
        "channelTitle": "Google Developers",
        "localized": {
          "title": "Meghan's Magical Playlist",
          "description": "Meet Meghan Mehta, a Developer Relations Engineer on the Android team working on Android education, Security, and Privacy. \n\nWe asked her to create a playlist of her must watch videos, she delivered a playlist full of fun and educational content ranging from all things Android, gymnastics, and music. Thanks Meghan!\n#WhatDevelopersWatch\n\nSubscribe to Google Developers → https://goo.gle/developers\n\nSubscribe to Android Developers → https://goo.gle/androiddevs"
        }
      },
      "contentDetails": {
        "itemCount": 9
      }
    }
  ]
}
```
---
### Get the list of videos in a Playlist
**Request:**
```
curl \
  'https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet%2CcontentDetails&maxResults=25&playlistId=PLBCF2DAC6FFB574DE&key=[YOUR_API_KEY]' \
  --header 'Authorization: Bearer [YOUR_ACCESS_TOKEN]' \
  --header 'Accept: application/json' \
  --compressed
```

**Response Example:**
```
{
  "kind": "youtube#playlistItemListResponse",
  "etag": "9-mLIZrrkELhhAuGgU-3qLiYT7M",
  "items": [
    {
      "kind": "youtube#playlistItem",
      "etag": "WyVabC0u-bz5tEiayi87X1303Fo",
      "id": "UExPVTJYTFl4bXNJS0JpcHVzWFl6TTNEWEtaYXlscmVPMi4yODlGNEE0NkRGMEEzMEQy",
      "snippet": {
        "publishedAt": "2021-05-20T23:55:17Z",
        "channelId": "UC_x5XG1OV2P6uZZ5FSM9Ttw",
        "title": "What's new in Google Pay | Keynote",
        "description": "Google Pay re-launched in 2020 with a redesigned app that enables brands to build deeper, more personal relationships with their customers. Meet the Google Pay team and learn how you can build richer digital payment experiences to acquire new users and better serve existing ones.\n\nResources:\nGoogle Pay Business Console → https://goo.gle/pay-console\nImprovements in the Google Pay integration experience → https://goo.gle/pay-integration-experience\nGoogle Pay developer documentation → https://goo.gle/pay-api-sca\nOne-click loyalty sign ups/sign-ins with Google Pay  → https://goo.gle/3eNnSED\n\nSpeaker: Archana Malhotra\n\nWatch more:\nGoogle Pay at Google I/O 2021 → https://goo.gle/pay-io21-playlist\nGoogle Developers at Google I/O 2021 Playlist → https://goo.gle/io21-GoogleDevelopers\nAll Google I/O 2021 Keynotes → https://goo.gle/io21-keynotes\nAll Google I/O 2021 Sessions → https://goo.gle/io21-allsessions\n\nSubscribe to Google Developers → https://goo.gle/developers\n\n\n #GoogleIO #Payments #Android #Web\n\n\nproduct: Google Pay - Business Console; event: Google I/O 2021; fullname: Archana Malhotra; re_ty: Premiere;",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/j9NBCig20Tw/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/j9NBCig20Tw/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/j9NBCig20Tw/hqdefault.jpg",
            "width": 480,
            "height": 360
          },
          "standard": {
            "url": "https://i.ytimg.com/vi/j9NBCig20Tw/sddefault.jpg",
            "width": 640,
            "height": 480
          },
          "maxres": {
            "url": "https://i.ytimg.com/vi/j9NBCig20Tw/maxresdefault.jpg",
            "width": 1280,
            "height": 720
          }
        },
        "channelTitle": "Google Developers",
        "playlistId": "PLOU2XLYxmsIKBipusXYzM3DXKZaylreO2",
        "position": 0,
        "resourceId": {
          "kind": "youtube#video",
          "videoId": "j9NBCig20Tw"
        },
        "videoOwnerChannelTitle": "Google Developers",
        "videoOwnerChannelId": "UC_x5XG1OV2P6uZZ5FSM9Ttw"
      },
      "contentDetails": {
        "videoId": "j9NBCig20Tw",
        "videoPublishedAt": "2021-05-19T21:13:12Z"
      }
    }
  ],
  "pageInfo": {
    "totalResults": 8,
    "resultsPerPage": 25
  }
}
```
---
### Get the details for a  video

**Request:**
```
curl \
  'https://youtube.googleapis.com/youtube/v3/videos?part=snippet%2CcontentDetails%2Cstatistics&id=j9NBCig20Tw&key=[YOUR_API_KEY]' \
  --header 'Authorization: Bearer [YOUR_ACCESS_TOKEN]' \
  --header 'Accept: application/json' \
  --compressed
```
**Response example:**
```
{
  "kind": "youtube#videoListResponse",
  "etag": "n5--v4UHl2_uWmUc78GwckDDHbA",
  "items": [
    {
      "kind": "youtube#video",
      "etag": "U7pb3RkNM7seX4Hz2YD2NNKkJ_M",
      "id": "j9NBCig20Tw",
      "snippet": {
        "publishedAt": "2021-05-19T21:13:12Z",
        "channelId": "UC_x5XG1OV2P6uZZ5FSM9Ttw",
        "title": "What's new in Google Pay | Keynote",
        "description": "Google Pay re-launched in 2020 with a redesigned app that enables brands to build deeper, more personal relationships with their customers. Meet the Google Pay team and learn how you can build richer digital payment experiences to acquire new users and better serve existing ones.\n\nResources:\nGoogle Pay Business Console → https://goo.gle/pay-console\nImprovements in the Google Pay integration experience → https://goo.gle/pay-integration-experience\nGoogle Pay developer documentation → https://goo.gle/pay-api-sca\nOne-click loyalty sign ups/sign-ins with Google Pay  → https://goo.gle/3eNnSED\n\nSpeaker: Archana Malhotra\n\nWatch more:\nGoogle Pay at Google I/O 2021 → https://goo.gle/pay-io21-playlist\nGoogle Developers at Google I/O 2021 Playlist → https://goo.gle/io21-GoogleDevelopers\nAll Google I/O 2021 Keynotes → https://goo.gle/io21-keynotes\nAll Google I/O 2021 Sessions → https://goo.gle/io21-allsessions\n\nSubscribe to Google Developers → https://goo.gle/developers\n\n\n #GoogleIO #Payments #Android #Web\n\n\nproduct: Google Pay - Business Console; event: Google I/O 2021; fullname: Archana Malhotra; re_ty: Premiere;",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/j9NBCig20Tw/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/j9NBCig20Tw/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/j9NBCig20Tw/hqdefault.jpg",
            "width": 480,
            "height": 360
          },
          "standard": {
            "url": "https://i.ytimg.com/vi/j9NBCig20Tw/sddefault.jpg",
            "width": 640,
            "height": 480
          },
          "maxres": {
            "url": "https://i.ytimg.com/vi/j9NBCig20Tw/maxresdefault.jpg",
            "width": 1280,
            "height": 720
          }
        },
        "channelTitle": "Google Developers",
        "tags": [
          "purpose: Educate",
          "type: Conference Talk (Full production)",
          "pr_pr: Google I/O",
          "Google Pay",
          "Google Pay what’s new",
          "what’s new Google Pay",
          "Google Pay 2021",
          "Google Pay updates",
          "Google Pay redesign",
          "Google pay brands",
          "Google tickets",
          "android payment",
          "android payments",
          "android development",
          "android developer",
          "web developer",
          "web development",
          "#GoogleIO",
          "Google I/O",
          "Google IO",
          "Google developer conference",
          "Google announcement",
          "Google conference",
          "Google",
          "developers"
        ],
        "categoryId": "28",
        "liveBroadcastContent": "none",
        "defaultLanguage": "en",
        "localized": {
          "title": "What's new in Google Pay | Keynote",
          "description": "Google Pay re-launched in 2020 with a redesigned app that enables brands to build deeper, more personal relationships with their customers. Meet the Google Pay team and learn how you can build richer digital payment experiences to acquire new users and better serve existing ones.\n\nResources:\nGoogle Pay Business Console → https://goo.gle/pay-console\nImprovements in the Google Pay integration experience → https://goo.gle/pay-integration-experience\nGoogle Pay developer documentation → https://goo.gle/pay-api-sca\nOne-click loyalty sign ups/sign-ins with Google Pay  → https://goo.gle/3eNnSED\n\nSpeaker: Archana Malhotra\n\nWatch more:\nGoogle Pay at Google I/O 2021 → https://goo.gle/pay-io21-playlist\nGoogle Developers at Google I/O 2021 Playlist → https://goo.gle/io21-GoogleDevelopers\nAll Google I/O 2021 Keynotes → https://goo.gle/io21-keynotes\nAll Google I/O 2021 Sessions → https://goo.gle/io21-allsessions\n\nSubscribe to Google Developers → https://goo.gle/developers\n\n\n #GoogleIO #Payments #Android #Web\n\n\nproduct: Google Pay - Business Console; event: Google I/O 2021; fullname: Archana Malhotra; re_ty: Premiere;"
        },
        "defaultAudioLanguage": "en-US"
      },
      "contentDetails": {
        "duration": "PT13M23S",
        "dimension": "2d",
        "definition": "hd",
        "caption": "true",
        "licensedContent": false,
        "contentRating": {},
        "projection": "rectangular"
      },
      "statistics": {
        "viewCount": "13375",
        "likeCount": "326",
        "dislikeCount": "13",
        "favoriteCount": "0",
        "commentCount": "32"
      }
    }
  ],
  "pageInfo": {
    "totalResults": 1,
    "resultsPerPage": 1
  }
}
```

## Database

The following diagram shows the structure of the database where the Monitor Service will be saving data.

![Database ER diagram (crow's foot)](https://user-images.githubusercontent.com/7916640/136282160-b51b7417-3964-4da5-961f-d1609a661fa4.png)

## Downloading videos

### Download initiator service

The initiator service will be created as AWS Lambda that will monitor new videos that need to be processed.

Initiator service will be scheduled to run in predefined time intervals and it will select a batch of new videos that need to be downloaded.

Prioritization of videos to be downloaded in each branch will be done based on:
1. Number of views
2. Number of likes
3. Time since discovery

The initiator service will then create a download request to spin a new docker container for each downloader.

### Downloader service

Downloader Service will be created as Kubernetes Docker Orchestration. The service can't be created as AWS Lambda because of specific limitations regarding file size and storage on Lambda instances. We should expect that videos can be very large.

Instead, the docker image will contain:
1. Node script to download the video file
2. Upload the video file to a dedicated AWS S3 bucket
3. Mark the video as "Ready" for further use in the DB

For downloading videos we will use existing library ```youtube-dl-exec``` which is a wrapper for a popular Open Source video downloading service.

**Example:**
```
import youtubedl from 'youtube-dl-exec';
const dl = youtubedl('https://www.youtube.com/watch?v=qroG2u4A2Q0', {}).then(output => console.log(output))
```

## Integration with other Joystream services

Other Joystream services that will be using downloaded videos can be integrated in several ways. For example:
1. Downloader service can invoke a dedicated API endpoint on any other system, informing it that there is a new video available in the system
2. Downloader service can push a message to shared Message Queue where multiple external system can be subscribed for notification of a new video

Other services can download the video and thumbnails from AWS S3 Bucket according to their needs.

**Comment by DzhideX** [comment]
I only really have a couple comments but looking at the grand scheme of things I think this approach makes a lot of sense and I agree with most of the decisions made here.

### Youtube Monitor Service Lambda:

I wanted to take the same approach initially but due to some problems I've moved to a different solution. That being said I am inexperienced when it comes to scaling though so my worries wrt it may be unfounded. 

The  potential problem I see is with the implications of polling at scale due to the [api quota](https://stackoverflow.com/questions/65748487/understanding-the-youtube-data-api-quota-limitations) set by Youtube. The base cap for a project is set to around 10,000 queries per day. Let's say we don't make the call every 5 minutes but if we assume one call per day. With an average of 200 videos per user (this is 4 points per user due to pagination), we only need 2500 users to reach the cap of allowed queries in that day. We can of course contact youtube and ask for more but that puts us at their hands and it is completely up to their discretion the amount of these points they are willing to give to us.

The general solution to problems related with polling are webhooks. Fortunately, Youtube does have their own implementation of this, they call them [Push Notifications](https://developers.google.com/youtube/v3/guides/push_notifications) and we could potentially use this instead of the polling approach. The problem is, the documentation is very much lacking when it comes to what the limits of the system are (i.e could we potentially track a million channels at once without any problems or would Youtube stop serving our route due to the high traffic). I've tried asking around on various places and even tried through their official system but I got this `"Let me add this in our feature request list but I can't guarantee that this feature will be implemented."` as a response to asking for these limits to be added to their docs. This approach would also tremendously lower the amount of times we would need to query the database as well so I think it may be worth looking into. Would love to hear your opinion on this (+ if you know anything I may have missed)! Also, I've implemented this in the repo already in case you want to take a peak at what it could possibly look like.

### Other:

I had some more concerns (mostly wrt the compatibility between this and Joystream) but Bedeho seems to have covered them quite well in his own comment above.

I don't have much more to add here as I think this would be a solid approach and from my POV we should be already be able to start coding this up. Also, if I've made any wrong implications on or misunderstood any part of the architecture it would be great if you could further explain so as to get more clarity on the whole thing.

**Comment by dselmanovic** [comment]
@DzhideX I think you made a good point regarding push notifications. Maybe it would even make sense to use both approaches and balance the load. I would love to see what you already have and give it a try.
