### ISSUE TITLE
Add field "jsg_verified" to the channels table on Dynamo

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/youtube-synch#120]
We want to add additional field `jsg_verified`, true/false. Which will be manually updated by YPP programme operated in Dynamo DB. This field will serve the purpose of tracking the manual review of the quality of channels participating, and ONLY verified channels will be included into the payload composition.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1203764263224995) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Lets jus overload the status field to have three cases, and no reference to "jsgenesis" as this codebase is/should be used by any gateway

- **unverified**: The default state status field. In this status, replication and synching should still occur.
- **suspended:** Synching does not happen. _Its not yet been determined how actually the operator updates this state._
- **verified:** Synching does happen. _Its not yet been determined how actually the operator updates this state_

The purpose of the last two variants is that they impact certain computational tools which are going to be specified in the near future, and since only these minor augmentations of the database representation were needed, it was worth incorporating it.

**Comment by zeeshanakram3** [comment]
FYI, currently, the channel's YPP status is managed using three states:

```ts
const ChannelYppStatus = ['Active', 'Suspended', 'OptedOut']
```

- **Active**: Assigned to the channel when a user becomes a participant in the YPP program after successful signup.
-  **Suspended**: The operator can set this field for channel/s, maybe due you violation of T&Cs. Yes, syncing does not happen for a suspended channel. An authenticated API endpoint is available for this action.
- **OptedOut**: Creators can deliberately opt out of the program. This action also stops syncing, API endpoint is also available for this action where the creator needs to  submit a signed message containing the flag and message timestamp.

So based on the current implementation, do you think we should transition the creator to an `Unverified` state instead of an `Active` state when he/she signs up for the program, and then transition to `Verified` should be after some manual verification through some API call (Ideally)?

**Comment by bedeho** [comment]
> FYI, currently, the channel's YPP status is managed using three states:

Oh great, this is already a rich representation then, I did not know that.

> So based on the current implementation, do you think we should transition the creator to an Unverified state instead of an Active state when he/she signs up for the program, and then transition to Verified should be after some manual verification through some API call (Ideally)?

Exactly sir 😎
