### ISSUE TITLE
Review content of Dynamo DB

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/youtube-synch#131]
@dmtrjsg commented on [Thu Jan 19 2023](https://github.com/Joystream/atlas/issues/3644)

After reviewing dynamo DB entries and in preparation for payouts management

## Scope
- [ ] Channel description seems to be empty now - populate
- [ ] "Created At" field is not readable - display as calendar date

⛔ out of scope:
- [x] Add synced category name (not just code)
- [x] Add joystream channel name (not just ID). Add next to joystream ID. 

Question: 
❓ 1. Is it worth adding "is_verified?" similarly to "is_suspended"? At some point probably good to display "verified badge": 
- https://github.com/Joystream/atlas/issues/3645

❓ 2. How to view statistics of synced videos at a certain point in time. 

## Context

Few observations:

![Screenshot 2023-01-19 at 16.10.01.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/d0908af7-32a2-4704-b0df-8add2461b294)

![Screenshot 2023-01-19 at 16.11.17.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/ed0c148c-af40-4203-afdf-71654c06cc9b)

![Screenshot 2023-01-19 at 16.09.55.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/17c9ee4d-4a51-48c9-b433-951781fb2a32)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203868726963296/1203869312261620) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
@zeeshanakram3 can you pls have a look and answer the questions raised there? Thank you sir 🙏

**Comment by zeeshanakram3** [comment]
> ❓ 1. Is it worth adding "is_verified?" similarly to "is_suspended"? At some point probably good to display "verified badge":

1. I think `is_suspended` is outdated/redundant which will not be set on new channels because of the same reason I described in [discord](https://discord.com/channels/811216481340751934/1035125759687266364/1065871010651439124) 2. we decided to add [Verified/Unverified](https://github.com/Joystream/youtube-synch/issues/120#issuecomment-1382251908) variant to `yppStatus` field.
>❓ 2. How to view statistics of synced videos at a certain point in time.
Can we please elaborate further? What statistics related to synced videos? we have an endpoint(`channels/{jsVideoId}/videos`) to list all the videos that ypp backend has for a specific JS channel.

**Comment by dmtrjsg** [comment]
@drillprop do we use `is_suspended` or `ypp_status` column to display suspended status on the dashboard? If the former we need to update it as this field is getting deprecated. 

Internal note: 
Fetching:
https://e35ed5hmoi.execute-api.us-east-1.amazonaws.com/stage/channels/27
https://e35ed5hmoi.execute-api.us-east-1.amazonaws.com/stage/channels/27/videos
