### ISSUE TITLE
Investigate auto-sync issues on atlas-dev

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/youtube-synch#146]
Autosync wasn't working for old and new channels

1. channelId 61 - newly created channel videos not syncing
2. channelId 55 - Manually updarting flag for syncing did not work. (After unsuspending the autosync remained disabled and it was not possible to enable it from settings, so we;'ve updated it manually). Relevant issue raised and added to bl
3. Channel 47 - new videos didn't sync, but old ones manually uploaded to platform for some reason showed up with failed upload tiles.. prob worth collaborating with @drillprop to investigate

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203868726963296/1203939935750980) by [Unito](https://www.unito.io)

**Comment by drillprop** [comment]
> 3. Channel 47 - new videos didn't sync, but old ones manually uploaded to platform for some reason showed up with failed upload tiles.. prob worth collaborating with @drillprop to investigate

I checked your channel, and I'm guessing that's not related to ypp. Is it possible for YPP backend to edit existing videos @zeeshanakram3 created on the atlas side(not youtube)? 
These videos assets have the status `isAccepted` set to false in QN, that's why they are displayed as failed videos. Probably something bad happened when you uploaded them. Do you remember if they worked before? 
![image](https://user-images.githubusercontent.com/51168865/218044758-c71cd8f8-4b64-40f9-bcca-306dfbd13c7d.png)
![image](https://user-images.githubusercontent.com/51168865/218045241-43e864dd-85fd-4b8b-aec9-65c99e8b11c1.png)
