### ISSUE TITLE
Effectively choose content for automated syncing

### ISSUE THREAD

**Issue by zeeshanakram3** [Joystream/youtube-synch#37]
## Background

#24 takes a dig into youtube-sync infrastructure scaling & latency issues. As, we don't want to overburden the blockchain infrastructure itself to such an extent that there is degraded experience for real user interactions, e.g., metaprotocol actions, forums, etc, and other DAO-related activities (council, proposals etc). 
Al the scale of syncing the videos of channels in an order of thousands to 100s of thousands, the synch infrastructure would have to the employ clever tricks so that 1) aggressive syncing don't overwhelms the blockchain itself 2) and the syncing process also accommodates maximum number of creators. Hence, we need to prioritize the videos syncing of each channels based on some filtration criteria( described below), so that the syncing infrastructure has maximum reach in terms of number of channels being actively synched

## Proposal
- Prioritize all new channels that opted in for the syncing, so every channel should have at least one video synced
- Probably we should not favourable to syncing only one channel's videos
- At scale of thousands of channels we should selectively choose which videos of a given channel we want to sync based on video's **Engagement Level**. We can define video engagement level based on different criteria. e.g. video likes/views/ count, when it was uploaded(probably should prioritize new uploads over the old ones). Inclusion of video duration (prioritizing small videos) in the selection criteria would also serve well for the sync infrastructure

## Solution
Manage multiple queues with each queue having priority relative to other for uploading videos to the Joystream network, and based on the priority of the video we can put video in respective queue. Next there are two options: 
- A queue with higher priority should be completely processed before we move to low priority queue
- Or maybe we can have different processing rates for different queues. E.g. queue with higher priority should have 2x processing rate compared to queue with low priority

---
We should let the creators know that **hey** we are following your videos in the system ,and it will probably take estimated `x` amount of for a specific video to be uploaded to Joystream. Basically for every video in the system there would be an expected upload timestamp calculated based on video position in the queue and its duration.

**Comment by bedeho** [comment]
I don't think you really need multiple queues here, why not just one [priority queue](https://en.wikipedia.org/wiki/Priority_queue) that orderes videos by some ordering metric reflecting what we care about. I also think your proposal is a good start, but it seems too vague, in particular the second point. Here is a fully operationalised version

```js
const MAX_SUDO_PRIORTITY;
const MAX_VIEWS_ON_YOUTUBE;
const MAX_VIDEO_RANK = measure(MAX_SUDO_PRIORTITY, 100, MAX_VIEWS_ON_YOUTUBE);

/**
 * The rank of a video.
 * 
 * @param {Number}	sudoPriority 							Exogenous prioritizatin of video, for example because creator is from a preferred category, in integer range [0, MAX_SUDO_PRIORTITY].
 * @param {Number}	percentageOfCreatorBacklogNotSynched	Percentage of all videos that should be synched for this creator (which need not be all videos that are on youtube for this creator), how many have actually been synched at this point, in integer range [0, 100].
 * @param {Number} 	viewsOnYouTube							The number of views on YouTube for this video, integer in range [0, MAX_VIEWS_ON_YOUTUBE].
 
 * @return {Number} 										Rank of a video, integer in range [0, MAX_VIDEO_RANK].
 */
funtion videoRank(sudoPriority: Number, percentageOfCreatorBacklogNotSynched: Number, viewsOnYouTube: Number) {

	if(isIntegerInRange(sudoPriority, 0, MAX_SUDO_PRIORTITY))
		throw Exception('Invalid sudoPriority');
	else if(isIntegerInRange(percentageOfCreatorBacklogNotSynched, 0, 100))
		throw Exception('Invalid percentageOfCreatorBacklogNotSynched');
	else if(isIntegerInRange(viewsOnYouTube, 0, MAX_VIEWS_ON_YOUTUBE))
		throw Exception('Invalid viewsOnYouTube');

	let rank = measure(sudoPriority, percentageOfCreatorBacklogNotSynched, viewsOnYouTube);

	assert(rank >= 0);
	assert(rank <= MAX_VIDEO_RANK);

	return rank;
}

function measure(x, y, z)  {
	return x*[100*[MAX_VIEWS_ON_YOUTUBE + 1] + MAX_VIEWS_ON_YOUTUBE + 1] + y*[MAX_VIEWS_ON_YOUTUBE + 1] + z;	
}
```

This rank is computed for each video added tothe queue. Since one of the inputs to the rank is based on the state of the queue itself (x) it means you also have to recompute ALL video ranks from a given channel whenever a video is added or removed for that channel, but the computational overhead of this should not be a serious constraint. The idea of this particular ranking is very straight forward, it ranks three properties independently and strictly: priority > backlog not synched > views. Hence there is no tradeoff between properties, as that just gets very complicated to reason about right now. You can of course alter this in any way you see fit, but this seems to at least capture the basics of what we want pretty well.
