### ISSUE TITLE
Unhandled exception when trying to register user

### ISSUE THREAD

**Issue by kdembler** [Joystream/youtube-synch#59]
Getting this response when trying to create the user via `/users` POST:
```json
{"statusCode":400,"message":"Cannot read properties of undefined (reading 'eq') is invalid for the query operation.","error":"Bad Request"}
```

**Comment by zeeshanakram3** [comment]
So did some investigation and turns out that this issue only happens while initiating verification using atlas. The verification happens successfully if you do it using the sample app provided in the `youTube-synch` repo. The reason there that there is inconsistency b/w the permissions they ask, i.e. the `scopes` they include in the authorisation request to the Google Oauth API, although apparently both apps include the same scope in the request ([YT-synch app](https://github.com/Joystream/youtube-synch/blob/dd3c008c8267a5788d09e1d95a0e8cf1d814ae0b/packages/app/src/app/app.tsx#L60) vs [Atlas](https://github.com/Joystream/atlas/blob/b7af86f9e6eb289ac42a80fee6239265833a2cb4/packages/atlas/src/views/global/YppLandingView/YppAuthorizationModal/YppAuthorizationModal.hooks.tsx#L34)). 

Turns out that `useGoogleLogin` function which sample app uses, is automatically including two extra scopes in the requests mainly for user ID and email info, that's, why the following line in the `/users` endpoint request handler succeeds because it contains valid user ID  in case of yt-synch app. While for Atlas user ID is undefined

```ts
const [registeredChannel] = await this.channelsService.getAll(user.id)
```

I have create an [Atlas PR](https://github.com/Joystream/atlas/pull/3478) for adding this extra scope, so that user ID isn't missing in the user object returned from the API.

**Comment by kdembler** [comment]
Nice! Merged the fix for Atlas, but maybe we should add more explicit handling of this error to the backend? So if we forget to include this scope, the error isn't so enigmatic?
